---
# tasks file for zabbix

- name: zabbix | copy new nginx.conf
  become: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes

- name: zabbix | open http port
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: zabbix | open https port
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: zabbix | insert php.ini
  copy:
    src: php.ini
    dest: /etc/opt/remi/php74/php.ini
    backup: yes

- name: zabbix | restart php-fpm
  service:
    name: php74-php-fpm
    state: restarted

- name: zabbix | install zabbix service and agent
  yum:
    name: ['zabbix-server-mysql', 'zabbix-web-mysql', 'zabbix-agent']

- name: Create zabbix database
  mysql_db:
    name: zabbix
    state: present
    collation: utf8_bin
    encoding: utf8

- name: Create zabbix database user
  mysql_user:
    name: zabbix
    password: 123
    priv: zabbix.*:ALL
    host: localhost
    state: present

- name: zabbix | copy db schema
  raw: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p123 zabbix

- name: zabbix | edit zabbix_server.conf
  lineinfile: 
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^DBPassword='
    line: 'DBPassword=123'

- name: zabbix-server | open ports
  firewalld:
    service: zabbix-server
    permanent: true
    immediate: yes
    state: enabled
  ignore_errors: yes

- name: zabbix | restart firewalld
  service:
    name: firewalld
    state: restarted

- name: zabbix | add zabbix SE rules
  shell: |
    setsebool -P httpd_can_connect_zabbix=1
    curl https://support.zabbix.com/secure/attachment/53320/zabbix_server_add.te > zabbix_server_add.te
    checkmodule -M -m -o zabbix_server_add.mod zabbix_server_add.te
    semodule_package -m zabbix_server_add.mod -o zabbix_server_add.pp
    semodule -i zabbix_server_add.pp

- name: zabbix | start and enable zabbix-server
  service:
    name: zabbix-server
    state: started
    enabled: yes

- name: zabbix | start and enable zabbix-agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes

- name: zabbix | stop and disable apachie
  service:
    name: httpd
    state: stopped
    enabled: no

- name: zabbix | restart and enable nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: zabbix | restart and enable php
  service:
    name: php74-php-fpm
    state: restarted
    enabled: yes
